### ISSUE TITLE
Outdated Tentative Weekly Schedule 

### ISSUE THREAD

**Issue by IsaiahLevy** [joannakl/ossd#105] opened 2024-03-08 18:11 UTC
The link to [Tentative Weekly Schedule](https://docs.google.com/spreadsheets/d/e/2PACX-1vQRPJ6qWpXkxBGd2Y16yRF7iQBc9xYjkj7Y6XKbEITUsndBUsvob4upOzoEcOdtqxKWGjVC60zQf85i/pubhtml?gid=114127910&single=true) on the home page directs to a fall 2023 schedule.

**Comment by joannakl** [comment] 2024-04-20 15:44
duplicate of #85

**Closed** 2024-04-20 15:44 UTC
